"""added complete

Revision ID: 6768746307c3
Revises: 586029edd929
Create Date: 2018-11-13 19:15:28.284969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6768746307c3'
down_revision = '586029edd929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('complete', sa.Boolean(), nullable=True))
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('todo', 'complete')
    # ### end Alembic commands ###
